use std::{borrow::Cow, collections::HashSet, hash::Hash, sync::Arc};

use async_graphql::{
    Error, Result,
    dynamic::{FieldValue, TypeRef},
};

use crate::Registrar;

/// The compile-time typed counterpart of a GraphQL output type.
///
/// Implemented once, by hand, for scalars/primitives in this crate (see
/// `scalar.rs`) and generated by `#[derive(SimpleObject)]` /
/// `#[Object]` / `#[derive(Enum)]` / etc. for user types. Every
/// implementation is meant to be small and non-generic in the *user's*
/// crate — the type-erased engine machinery lives on the other side of
/// `dynamic::FieldValue`/`dynamic::Object`, compiled once in this crate, so a
/// user edit only recompiles the tiny, non-generic `register`/resolver
/// closures a derive macro emits, never a generic engine (see the plan's
/// "Why async-graphql is slow to rebuild").
pub trait OutputType: Send + Sync + 'static {
    /// The bare GraphQL type name (`"Int"`, `"MyObject"`, ...).
    fn type_name() -> Cow<'static, str>;

    /// The full type reference as it appears in field position (`Int!`,
    /// `[MyObject!]`, ...). The default wraps `type_name()` in `NonNull` — a
    /// bare Rust type is non-null by default (matching async-graphql's own
    /// convention); the `Option<T>` blanket impl strips it back off.
    fn type_ref() -> TypeRef {
        TypeRef::NonNull(Box::new(TypeRef::named(Self::type_name())))
    }

    /// Register this type — and everything it transitively depends on
    /// (field return types) — into `registrar`. Implementations must call
    /// `registrar.visit::<Self>()` first and return immediately if it comes
    /// back `false` (already registered via some other path).
    fn register(registrar: &mut Registrar);

    /// Consume `self` and produce a `dynamic::FieldValue` for an async
    /// resolver (`FieldFuture::Future`) — the shape any field with an `async`
    /// body (arguments, a guard, a service call, ...) compiles down to.
    /// Returning `Ok(None)` means a GraphQL `null`; only the `Option<T>`
    /// blanket impl ever does that.
    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>>;

    /// Borrow `self` and produce a `dynamic::FieldValue` for a sync resolver
    /// (`FieldFuture::Value`) — the shape a plain `SimpleObject` getter (no
    /// args, no `.await`) compiles down to, so it can borrow through
    /// `FieldValue::borrowed_any`/`FieldValue::value` instead of cloning.
    ///
    /// Not every `OutputType` supports this — `Result<T, E>` in particular
    /// can only ever come from an async resolver body, so a field can never
    /// legally be typed `Result<T, E>` in a sync-getter position. Rather than
    /// silently doing something wrong, types that don't support it inherit
    /// this default, which errors clearly instead.
    fn resolve_ref(&self) -> Result<Option<FieldValue<'_>>> {
        Err(Error::new(format!(
            "`{}` (GraphQL `{}`) does not support synchronous field resolution; \
             it can only be returned from an async resolver",
            std::any::type_name::<Self>(),
            Self::type_name(),
        )))
    }
}

impl<T: OutputType> OutputType for Option<T> {
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn type_ref() -> TypeRef {
        match T::type_ref() {
            TypeRef::NonNull(inner) => *inner,
            other => other,
        }
    }

    fn register(registrar: &mut Registrar) {
        T::register(registrar);
    }

    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>> {
        match self {
            Some(v) => v.resolve_owned(),
            None => Ok(None),
        }
    }

    fn resolve_ref(&self) -> Result<Option<FieldValue<'_>>> {
        match self {
            Some(v) => v.resolve_ref(),
            None => Ok(None),
        }
    }
}

impl<T: OutputType> OutputType for Vec<T> {
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn type_ref() -> TypeRef {
        TypeRef::NonNull(Box::new(TypeRef::List(Box::new(T::type_ref()))))
    }

    fn register(registrar: &mut Registrar) {
        T::register(registrar);
    }

    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>> {
        let mut items = Vec::with_capacity(self.len());
        for item in self {
            items.push(item.resolve_owned()?.unwrap_or(FieldValue::NULL));
        }
        Ok(Some(FieldValue::list(items)))
    }

    fn resolve_ref(&self) -> Result<Option<FieldValue<'_>>> {
        let mut items = Vec::with_capacity(self.len());
        for item in self {
            items.push(item.resolve_ref()?.unwrap_or(FieldValue::NULL));
        }
        Ok(Some(FieldValue::list(items)))
    }
}

/// A plain field getter returning `HashSet<T>` directly (not a connection)
/// needs the same GraphQL-list shape as `Vec<T>` (matching real async-graphql's own `HashSet<T>`
/// `OutputType` impl, `types/external/hash_set.rs`: a set has no ordering
/// contract GraphQL cares about, so it prints exactly like a list).
impl<T: OutputType + Eq + Hash> OutputType for HashSet<T> {
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn type_ref() -> TypeRef {
        TypeRef::NonNull(Box::new(TypeRef::List(Box::new(T::type_ref()))))
    }

    fn register(registrar: &mut Registrar) {
        T::register(registrar);
    }

    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>> {
        let mut items = Vec::with_capacity(self.len());
        for item in self {
            items.push(item.resolve_owned()?.unwrap_or(FieldValue::NULL));
        }
        Ok(Some(FieldValue::list(items)))
    }

    fn resolve_ref(&self) -> Result<Option<FieldValue<'_>>> {
        let mut items = Vec::with_capacity(self.len());
        for item in self {
            items.push(item.resolve_ref()?.unwrap_or(FieldValue::NULL));
        }
        Ok(Some(FieldValue::list(items)))
    }
}

impl<T, E> OutputType for std::result::Result<T, E>
where
    T: OutputType,
    E: Into<Error> + Send + Sync + 'static,
{
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn type_ref() -> TypeRef {
        T::type_ref()
    }

    fn register(registrar: &mut Registrar) {
        T::register(registrar);
    }

    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>> {
        self.map_err(Into::into)?.resolve_owned()
    }

    // `resolve_ref` inherits the trait default (errors) — a fallible value
    // can only be produced by an async resolver body, never by a sync
    // `SimpleObject`-style getter, so this is never legally called.
}

impl<T: OutputType> OutputType for Box<T> {
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn type_ref() -> TypeRef {
        T::type_ref()
    }

    fn register(registrar: &mut Registrar) {
        T::register(registrar);
    }

    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>> {
        (*self).resolve_owned()
    }

    fn resolve_ref(&self) -> Result<Option<FieldValue<'_>>> {
        (**self).resolve_ref()
    }
}

/// Delegates to `T`. Note `resolve_owned` needs `T: Clone` — unlike `Box<T>`,
/// an owned `T` cannot generically be moved out of an `Arc<T>` (the refcount
/// may be > 1), so the owned path falls back to cloning when this isn't the
/// sole reference.
impl<T: OutputType + Clone> OutputType for Arc<T> {
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn type_ref() -> TypeRef {
        T::type_ref()
    }

    fn register(registrar: &mut Registrar) {
        T::register(registrar);
    }

    fn resolve_owned(self) -> Result<Option<FieldValue<'static>>> {
        Arc::try_unwrap(self)
            .unwrap_or_else(|arc| (*arc).clone())
            .resolve_owned()
    }

    fn resolve_ref(&self) -> Result<Option<FieldValue<'_>>> {
        (**self).resolve_ref()
    }
}
