//! `SubscriptionRoot` — the third [`crate::Schema::build`] slot's trait,
//! parallel to [`crate::RootFields`] but building a `dynamic::Subscription`
//! instead of a `dynamic::Object`.
//!
//! Split out from `RootFields` (rather than reusing it) because a
//! subscription root is a genuinely different `dynamic` engine type — real
//! async-graphql's dynamic engine registers `Query`/`Mutation` via
//! `dynamic::Object` but `Subscription` via its own `dynamic::Subscription`/
//! `dynamic::SubscriptionField`/`dynamic::SubscriptionFieldFuture` (see
//! `async-graphql-7.0.17`'s `dynamic/subscription.rs`): every subscription
//! field resolves to a **stream** of values, not a single value, so its
//! resolver closure returns `SubscriptionFieldFuture` (`Future<Output =
//! Result<impl Stream<Item = Result<T>>>>`) rather than `FieldFuture`
//! (`Future<Output = Result<Option<FieldValue>>>`). This trait exists so a
//! subscription root can be introduced as a concern separate from
//! `RootFields`, for exactly this reason, without changing that trait's
//! shape.
//!
//! Implemented by hand only for [`crate::EmptySubscription`] (below); every
//! other implementor is generated by `#[Subscription] impl Foo { .. }`
//! (`flash-graphql-derive`'s `subscription.rs`), matching a typical
//! real-world subscription root shape: `#[Subscription] impl Subscription {
//! #[graphql(guard = "..")] async fn active_sessions(&self, ctx:
//! &Context<'_>) -> Result<impl Stream<Item = Vec<OnlineUser>>> { .. } async
//! fn build_info(&self) -> Result<impl Stream<Item = Version>> { .. } }` —
//! a zero-sized marker struct, same as `#[Object]`'s real-world usage (see
//! `flash-graphql-derive/src/object.rs`'s module doc), so the generated
//! `add_fields`/`register` never need `&self` either.
use async_graphql::dynamic;

use crate::{EmptySubscription, Registrar};

/// See the module docs.
pub trait SubscriptionRoot: Send + Sync + 'static {
    /// The GraphQL name of the subscription root (`"Subscription"`, matching
    /// a typical zero-sized `struct Subscription;` marker).
    const NAME: &'static str;

    /// `true` for [`EmptySubscription`] — tells [`crate::Schema::build`] to
    /// skip building/registering a `dynamic::Subscription` entirely and pass
    /// `None` for the subscription root's name to the underlying
    /// `dynamic::Schema::build`.
    const IS_EMPTY: bool = false;

    /// Add this root's fields onto `subscription` (already constructed and
    /// named `Self::NAME`).
    #[must_use]
    fn add_fields(subscription: dynamic::Subscription) -> dynamic::Subscription {
        subscription
    }

    /// Register every type reachable from this root's fields (stream item
    /// types, argument types) into `registrar`.
    fn register(_registrar: &mut Registrar) {}
}

impl SubscriptionRoot for EmptySubscription {
    const NAME: &'static str = "Subscription";
    const IS_EMPTY: bool = true;
}
